using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:55:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.Models.Sys
{    
    /// <summary>
    /// SysExceptionModel
    /// </summary>
    public class SysExceptionModel    
    {    
        /// <summary>
          ///编号
          /// </summary>
          [NotNullExpression]
          [Required]
          [MaxWordsExpression(50)]
          [Display(Name="编号")]
          public string Id { get; set; }
          /// <summary>
          ///帮助链接
          /// </summary>
          [MaxWordsExpression(500)]
          [Display(Name="帮助链接")]
          public string HelpLink { get; set; }
          /// <summary>
          ///异常信息
          /// </summary>
          [MaxWordsExpression(500)]
          [Display(Name="异常信息")]
          public string Message { get; set; }
          /// <summary>
          ///错误信息
          /// </summary>
          [MaxWordsExpression(500)]
          [Display(Name="错误信息")]
          public string Source { get; set; }
          /// <summary>
          ///错误堆栈
          /// </summary>
          [MaxWordsExpression(16)]
          [Display(Name="错误堆栈")]
          public string StackTrace { get; set; }
          /// <summary>
          ///目标页
          /// </summary>
          [MaxWordsExpression(500)]
          [Display(Name="目标页")]
          public string TargetSite { get; set; }
          /// <summary>
          ///程序集
          /// </summary>
          [MaxWordsExpression(500)]
          [Display(Name="程序集")]
          public string Data { get; set; }
          /// <summary>
          ///发生时间
          /// </summary>
          [DateExpression]
          [MaxWordsExpression(8)]
          [Display(Name="发生时间")]
          public DateTime? CreateTime { get; set; }

    }
}
    
