using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:55:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.Models.Sys
{    
    /// <summary>
    /// SysModuleModel
    /// </summary>
    public class SysModuleModel    
    {    
        /// <summary>
          ///编号
          /// </summary>
          [NotNullExpression]
          [Required]
          [MaxWordsExpression(50)]
          [Display(Name="编号")]
          public string Id { get; set; }
          /// <summary>
          ///模块名
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="模块名")]
          public string Name { get; set; }
          /// <summary>
          ///英文名称
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="英文名称")]
          public string EnglishName { get; set; }
          /// <summary>
          ///父级编号
          /// </summary>
          [MaxWordsExpression(50)]
          [Display(Name="父级编号")]
          public string ParentId { get; set; }
          /// <summary>
          ///URL
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="URL")]
          public string Url { get; set; }
          /// <summary>
          ///图标
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="图标")]
          public string Iconic { get; set; }
          /// <summary>
          ///排序
          /// </summary>
          [MaxWordsExpression(4)]
          [Display(Name="排序")]
          public int? Sort { get; set; }
          /// <summary>
          ///备注
          /// </summary>
          [MaxWordsExpression(4000)]
          [Display(Name="备注")]
          public string Remark { get; set; }
          /// <summary>
          ///状态
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(1)]
          [Display(Name="状态")]
          public bool Enable { get; set; }
          /// <summary>
          ///创建人
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="创建人")]
          public string CreatePerson { get; set; }
          /// <summary>
          ///创建时间
          /// </summary>
          [DateExpression]
          [MaxWordsExpression(8)]
          [Display(Name="创建时间")]
          public DateTime? CreateTime { get; set; }
          /// <summary>
          ///是否是最后
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(1)]
          [Display(Name="是否是最后")]
          public bool IsLast { get; set; }
          /// <summary>
          ///版本
          /// </summary>
          [MaxWordsExpression(8)]
          [Display(Name="版本")]
          public byte[] Version { get; set; }

    }
}
    
