using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:55:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.Models.Sys
{    
    /// <summary>
    /// SysModuleOperateModel
    /// </summary>
    public class SysModuleOperateModel    
    {    
        /// <summary>
          ///ID
          /// </summary>
          [NotNullExpression]
          [Required]
          [MaxWordsExpression(200)]
          [Display(Name="ID")]
          public string Id { get; set; }
          /// <summary>
          ///操作名称
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="操作名称")]
          public string Name { get; set; }
          /// <summary>
          ///操作码
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="操作码")]
          public string KeyCode { get; set; }
          /// <summary>
          ///所属模块
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(50)]
          [Display(Name="所属模块")]
          public string ModuleId { get; set; }
          /// <summary>
          ///是否验证
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(1)]
          [Display(Name="是否验证")]
          public bool IsValid { get; set; }
          /// <summary>
          ///排序号
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(4)]
          [Display(Name="排序号")]
          public int Sort { get; set; }

    }
}
    
