using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:55:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.Models.Sys
{    
    /// <summary>
    /// SysRightOperateModel
    /// </summary>
    public class SysRightOperateModel    
    {    
        /// <summary>
          ///
          /// </summary>
          [NotNullExpression]
          [Required]
          [MaxWordsExpression(200)]
          [Display(Name="Id?")]
          public string Id { get; set; }
          /// <summary>
          ///
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="RightId?")]
          public string RightId { get; set; }
          /// <summary>
          ///
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="KeyCode?")]
          public string KeyCode { get; set; }
          /// <summary>
          ///
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(1)]
          [Display(Name="IsValid?")]
          public bool IsValid { get; set; }

    }
}
    
