using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:55:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.Models.Sys
{    
    /// <summary>
    /// SysRoleModel
    /// </summary>
    public class SysRoleModel    
    {    
        /// <summary>
          ///角色编码
          /// </summary>
          [NotNullExpression]
          [Required]
          [MaxWordsExpression(50)]
          [Display(Name="角色编码")]
          public string Id { get; set; }
          /// <summary>
          ///角色名
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="角色名")]
          public string Name { get; set; }
          /// <summary>
          ///描述
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(4000)]
          [Display(Name="描述")]
          public string Description { get; set; }
          /// <summary>
          ///创建时间
          /// </summary>
          [DateExpression]
          [NotNullExpression]
          [MaxWordsExpression(8)]
          [Display(Name="创建时间")]
          public DateTime CreateTime { get; set; }
          /// <summary>
          ///创建人
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="创建人")]
          public string CreatePerson { get; set; }

    }
}
    
