using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:55:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.Models.Sys
{    
    /// <summary>
    /// SysSampleModel
    /// </summary>
    public class SysSampleModel    
    {    
        /// <summary>
          ///
          /// </summary>
          [NotNullExpression]
          [Required]
          [MaxWordsExpression(4)]
          [Display(Name="Id?")]
          public int Id { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(50)]
          [Display(Name="Name?")]
          public string Name { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(4)]
          [Display(Name="Age?")]
          public int? Age { get; set; }
          /// <summary>
          ///
          /// </summary>
          [DateExpression]
          [MaxWordsExpression(8)]
          [Display(Name="Bir?")]
          public DateTime? Bir { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(50)]
          [Display(Name="Photo?")]
          public string Photo { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(16)]
          [Display(Name="Note?")]
          public string Note { get; set; }
          /// <summary>
          ///
          /// </summary>
          [DateExpression]
          [MaxWordsExpression(8)]
          [Display(Name="CreateTime?")]
          public DateTime? CreateTime { get; set; }

    }
}
    
