using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:55:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.Models.Sys
{    
    /// <summary>
    /// SysUserModel
    /// </summary>
    public class SysUserModel    
    {    
        /// <summary>
          ///
          /// </summary>
          [NotNullExpression]
          [Required]
          [MaxWordsExpression(50)]
          [Display(Name="Id?")]
          public string Id { get; set; }
          /// <summary>
          ///
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="UserName?")]
          public string UserName { get; set; }
          /// <summary>
          ///
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(200)]
          [Display(Name="Password?")]
          public string Password { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="TrueName?")]
          public string TrueName { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(50)]
          [Display(Name="Card?")]
          public string Card { get; set; }
          /// <summary>
          ///身份证
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="身份证")]
          public string MobileNumber { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="PhoneNumber?")]
          public string PhoneNumber { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(50)]
          [Display(Name="QQ?")]
          public string QQ { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="EmailAddress?")]
          public string EmailAddress { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="OtherContact?")]
          public string OtherContact { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="Province?")]
          public string Province { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="City?")]
          public string City { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="Village?")]
          public string Village { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="Address?")]
          public string Address { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(1)]
          [Display(Name="State?")]
          public bool? State { get; set; }
          /// <summary>
          ///
          /// </summary>
          [DateExpression]
          [MaxWordsExpression(8)]
          [Display(Name="CreateTime?")]
          public DateTime? CreateTime { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="CreatePerson?")]
          public string CreatePerson { get; set; }
          /// <summary>
          ///
          /// </summary>
          [MaxWordsExpression(10)]
          [Display(Name="Sex?")]
          public string Sex { get; set; }
          /// <summary>
          ///
          /// </summary>
          [DateExpression]
          [MaxWordsExpression(8)]
          [Display(Name="Birthday?")]
          public DateTime? Birthday { get; set; }
          /// <summary>
          ///
          /// </summary>
          [DateExpression]
          [MaxWordsExpression(8)]
          [Display(Name="JoinDate?")]
          public DateTime? JoinDate { get; set; }
          /// <summary>
          ///婚姻
          /// </summary>
          [MaxWordsExpression(10)]
          [Display(Name="婚姻")]
          public string Marital { get; set; }
          /// <summary>
          ///党派
          /// </summary>
          [MaxWordsExpression(50)]
          [Display(Name="党派")]
          public string Political { get; set; }
          /// <summary>
          ///民族
          /// </summary>
          [MaxWordsExpression(20)]
          [Display(Name="民族")]
          public string Nationality { get; set; }
          /// <summary>
          ///籍贯
          /// </summary>
          [MaxWordsExpression(20)]
          [Display(Name="籍贯")]
          public string Native { get; set; }
          /// <summary>
          ///毕业学校
          /// </summary>
          [MaxWordsExpression(50)]
          [Display(Name="毕业学校")]
          public string School { get; set; }
          /// <summary>
          ///就读专业
          /// </summary>
          [MaxWordsExpression(100)]
          [Display(Name="就读专业")]
          public string Professional { get; set; }
          /// <summary>
          ///学历
          /// </summary>
          [MaxWordsExpression(20)]
          [Display(Name="学历")]
          public string Degree { get; set; }
          /// <summary>
          ///部门
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(50)]
          [Display(Name="部门")]
          public string DepId { get; set; }
          /// <summary>
          ///职位
          /// </summary>
          [NotNullExpression]
          [MaxWordsExpression(50)]
          [Display(Name="职位")]
          public string PosId { get; set; }
          /// <summary>
          ///个人简介
          /// </summary>
          [MaxWordsExpression(3000)]
          [Display(Name="个人简介")]
          public string Expertise { get; set; }
          /// <summary>
          ///在职状况
          /// </summary>
          [MaxWordsExpression(20)]
          [Display(Name="在职状况")]
          public string JobState { get; set; }
          /// <summary>
          ///照片
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="照片")]
          public string Photo { get; set; }
          /// <summary>
          ///附件
          /// </summary>
          [MaxWordsExpression(200)]
          [Display(Name="附件")]
          public string Attach { get; set; }

    }
}
    
