


using System;
using System.Collections.Generic;
using Apps.IBLL;
using Apps.IDAL;
using Apps.Models;
using Apps.Models.Sys;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:20:12
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.BLL
{    
    
    /// <summary>
    /// SysModule 操作类
    /// </summary>
    public class SysModuleBLL: BaseBLL, ISysModuleBLL
    {

        

        public static SysModule Select(String id)
        {
            using(var context = db.Context())
            {
                return context.Sql(" SELECT * FROM SysModule WHERE Id = @id ")
                    .Parameter("id", id)

                    .QuerySingle<SysModule>();
            }
        }

        public static List<SysModule> SelectAll()
        {
            return SelectAll(string.Empty);
        }

        public static List<SysModule> SelectAll(string sortExpression)
        {
            return SelectAll(0, 0, sortExpression);
        }

        public static List<SysModule> SelectAll(int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysModule>(" * ")
                    .From(" SysModule ");

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountAll()
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysModule ")
                    .QuerySingle<int>();
            }
        }

        

        public static List<SysModule> SelectBySysModule(String parentId)
        {
            return SelectBySysModule(parentId, string.Empty);
        }

        public static List<SysModule> SelectBySysModule(String parentId, string sortExpression)
        {
            return SelectBySysModule(parentId, 0, 0, sortExpression);
        }

        public static List<SysModule> SelectBySysModule(String parentId, int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysModule>(" * ")
                    .From(" SysModule ")
                    .Where(" ParentId = @parentid ")
                    .Parameter("parentid", parentId);

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountBySysModule(String parentId)
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysModule WHERE ParentId = @parentid")
                    .Parameter("parentid", parentId)
                    .QuerySingle<int>();
            }
        }
        


        public static bool Insert(SysModule sysModule) 
        {
            using (var context =db.Context())
            {
                return context.Insert<SysModule>("SysModule", sysModule)
                    .Execute() > 0;
            }
        }

        public static bool Update(SysModule sysModule)
        {
            using (var context = db.Context())
            {
                return context.Update<SysModule>("SysModule", sysModule)
                    .AutoMap(x => x.Id)
                    
                    .Where("Id", sysModule.Id)
                    
                    .Execute() > 0;
            }
        }

        public static bool Delete(SysModule sysModule) 
        {
            return Delete(sysModule.Id);
        }

        public static bool Delete(String id)
        {
            using (var context = db.Context())
            {
                return context.Sql(" DELETE FROM Product WHERE Id = @id ")
                    .Parameter("id", id)

                    .Execute() > 0;
            }
        }
    }
    
}
    
