


using System;
using System.Collections.Generic;
using Apps.IBLL;
using Apps.IDAL;
using Apps.Models;
using Apps.Models.Sys;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:20:12
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.BLL
{    
    
    /// <summary>
    /// SysRight 操作类
    /// </summary>
    public class SysRightBLL: BaseBLL, ISysRightBLL
    {

        

        public static SysRight Select(String id)
        {
            using(var context = db.Context())
            {
                return context.Sql(" SELECT * FROM SysRight WHERE Id = @id ")
                    .Parameter("id", id)

                    .QuerySingle<SysRight>();
            }
        }

        public static List<SysRight> SelectAll()
        {
            return SelectAll(string.Empty);
        }

        public static List<SysRight> SelectAll(string sortExpression)
        {
            return SelectAll(0, 0, sortExpression);
        }

        public static List<SysRight> SelectAll(int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysRight>(" * ")
                    .From(" SysRight ");

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountAll()
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysRight ")
                    .QuerySingle<int>();
            }
        }

        

        public static List<SysRight> SelectBySysModule(String moduleId)
        {
            return SelectBySysModule(moduleId, string.Empty);
        }

        public static List<SysRight> SelectBySysModule(String moduleId, string sortExpression)
        {
            return SelectBySysModule(moduleId, 0, 0, sortExpression);
        }

        public static List<SysRight> SelectBySysModule(String moduleId, int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysRight>(" * ")
                    .From(" SysRight ")
                    .Where(" ModuleId = @moduleid ")
                    .Parameter("moduleid", moduleId);

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountBySysModule(String moduleId)
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysRight WHERE ModuleId = @moduleid")
                    .Parameter("moduleid", moduleId)
                    .QuerySingle<int>();
            }
        }
        

        public static List<SysRight> SelectBySysRole(String roleId)
        {
            return SelectBySysRole(roleId, string.Empty);
        }

        public static List<SysRight> SelectBySysRole(String roleId, string sortExpression)
        {
            return SelectBySysRole(roleId, 0, 0, sortExpression);
        }

        public static List<SysRight> SelectBySysRole(String roleId, int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysRight>(" * ")
                    .From(" SysRight ")
                    .Where(" RoleId = @roleid ")
                    .Parameter("roleid", roleId);

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountBySysRole(String roleId)
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysRight WHERE RoleId = @roleid")
                    .Parameter("roleid", roleId)
                    .QuerySingle<int>();
            }
        }
        


        public static bool Insert(SysRight sysRight) 
        {
            using (var context =db.Context())
            {
                return context.Insert<SysRight>("SysRight", sysRight)
                    .Execute() > 0;
            }
        }

        public static bool Update(SysRight sysRight)
        {
            using (var context = db.Context())
            {
                return context.Update<SysRight>("SysRight", sysRight)
                    .AutoMap(x => x.Id)
                    
                    .Where("Id", sysRight.Id)
                    
                    .Execute() > 0;
            }
        }

        public static bool Delete(SysRight sysRight) 
        {
            return Delete(sysRight.Id);
        }

        public static bool Delete(String id)
        {
            using (var context = db.Context())
            {
                return context.Sql(" DELETE FROM Product WHERE Id = @id ")
                    .Parameter("id", id)

                    .Execute() > 0;
            }
        }
    }
    
}
    
