


using System;
using System.Collections.Generic;
using Apps.IBLL;
using Apps.IDAL;
using Apps.Models;
using Apps.Models.Sys;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:20:12
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.BLL
{    
    
    /// <summary>
    /// SysRightOperate 操作类
    /// </summary>
    public class SysRightOperateBLL: BaseBLL, ISysRightOperateBLL
    {

        

        public static SysRightOperate Select(String id)
        {
            using(var context = db.Context())
            {
                return context.Sql(" SELECT * FROM SysRightOperate WHERE Id = @id ")
                    .Parameter("id", id)

                    .QuerySingle<SysRightOperate>();
            }
        }

        public static List<SysRightOperate> SelectAll()
        {
            return SelectAll(string.Empty);
        }

        public static List<SysRightOperate> SelectAll(string sortExpression)
        {
            return SelectAll(0, 0, sortExpression);
        }

        public static List<SysRightOperate> SelectAll(int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysRightOperate>(" * ")
                    .From(" SysRightOperate ");

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountAll()
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysRightOperate ")
                    .QuerySingle<int>();
            }
        }

        

        public static List<SysRightOperate> SelectBySysRight(String rightId)
        {
            return SelectBySysRight(rightId, string.Empty);
        }

        public static List<SysRightOperate> SelectBySysRight(String rightId, string sortExpression)
        {
            return SelectBySysRight(rightId, 0, 0, sortExpression);
        }

        public static List<SysRightOperate> SelectBySysRight(String rightId, int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysRightOperate>(" * ")
                    .From(" SysRightOperate ")
                    .Where(" RightId = @rightid ")
                    .Parameter("rightid", rightId);

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountBySysRight(String rightId)
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysRightOperate WHERE RightId = @rightid")
                    .Parameter("rightid", rightId)
                    .QuerySingle<int>();
            }
        }
        


        public static bool Insert(SysRightOperate sysRightOperate) 
        {
            using (var context =db.Context())
            {
                return context.Insert<SysRightOperate>("SysRightOperate", sysRightOperate)
                    .Execute() > 0;
            }
        }

        public static bool Update(SysRightOperate sysRightOperate)
        {
            using (var context = db.Context())
            {
                return context.Update<SysRightOperate>("SysRightOperate", sysRightOperate)
                    .AutoMap(x => x.Id)
                    
                    .Where("Id", sysRightOperate.Id)
                    
                    .Execute() > 0;
            }
        }

        public static bool Delete(SysRightOperate sysRightOperate) 
        {
            return Delete(sysRightOperate.Id);
        }

        public static bool Delete(String id)
        {
            using (var context = db.Context())
            {
                return context.Sql(" DELETE FROM Product WHERE Id = @id ")
                    .Parameter("id", id)

                    .Execute() > 0;
            }
        }
    }
    
}
    
