


using System;
using System.Collections.Generic;
using Apps.IBLL;
using Apps.IDAL;
using Apps.Models;
using Apps.Models.Sys;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:20:12
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.BLL
{    
    
    /// <summary>
    /// SysSample 操作类
    /// </summary>
    public class SysSampleBLL: BaseBLL, ISysSampleBLL
    {

        

        public static SysSample Select(Int32 id)
        {
            using(var context = db.Context())
            {
                return context.Sql(" SELECT * FROM SysSample WHERE Id = @id ")
                    .Parameter("id", id)

                    .QuerySingle<SysSample>();
            }
        }

        public static List<SysSample> SelectAll()
        {
            return SelectAll(string.Empty);
        }

        public static List<SysSample> SelectAll(string sortExpression)
        {
            return SelectAll(0, 0, sortExpression);
        }

        public static List<SysSample> SelectAll(int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysSample>(" * ")
                    .From(" SysSample ");

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountAll()
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysSample ")
                    .QuerySingle<int>();
            }
        }

        


        public static bool Insert(SysSample sysSample) 
        {
            using (var context = db.Context())
            {
                int id = context.Insert<SysSample>("SysSample", sysSample)
                    .AutoMap(x => x.Id)
                    .ExecuteReturnLastId<int>();

                sysSample.Id = id;
                return id > 0;
            }
        }

        public static bool Update(SysSample sysSample)
        {
            using (var context = db.Context())
            {
                return context.Update<SysSample>("SysSample", sysSample)
                    .AutoMap(x => x.Id)
                    
                    .Where("Id", sysSample.Id)
                    
                    .Execute() > 0;
            }
        }

        public static bool Delete(SysSample sysSample) 
        {
            return Delete(sysSample.Id);
        }

        public static bool Delete(Int32 id)
        {
            using (var context = db.Context())
            {
                return context.Sql(" DELETE FROM Product WHERE Id = @id ")
                    .Parameter("id", id)

                    .Execute() > 0;
            }
        }
    }
    
}
    
