


using System;
using System.Collections.Generic;
using Apps.IBLL;
using Apps.IDAL;
using Apps.Models;
using Apps.Models.Sys;
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间2018-10-23 11:20:12
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apps.BLL
{    
    
    /// <summary>
    /// SysUser 操作类
    /// </summary>
    public class SysUserBLL: BaseBLL, ISysUserBLL
    {

        

        public static SysUser Select(String id)
        {
            using(var context = db.Context())
            {
                return context.Sql(" SELECT * FROM SysUser WHERE Id = @id ")
                    .Parameter("id", id)

                    .QuerySingle<SysUser>();
            }
        }

        public static List<SysUser> SelectAll()
        {
            return SelectAll(string.Empty);
        }

        public static List<SysUser> SelectAll(string sortExpression)
        {
            return SelectAll(0, 0, sortExpression);
        }

        public static List<SysUser> SelectAll(int startRowIndex, int maximumRows, string sortExpression)
        {
            using (var context = db.Context())
            {
                var select = context.Select<SysUser>(" * ")
                    .From(" SysUser ");

                if (maximumRows > 0)
                {
                    if (startRowIndex == 0) 
                        startRowIndex = 1;

                    select.Paging(startRowIndex, maximumRows);
                }

                if (!string.IsNullOrEmpty(sortExpression))
                    select.OrderBy(sortExpression);

                return select.QueryMany();
            }
        }

        public static int CountAll()
        {
            using (var context = db.Context())
            {
                return context.Sql(" SELECT COUNT(*) FROM SysUser ")
                    .QuerySingle<int>();
            }
        }

        


        public static bool Insert(SysUser sysUser) 
        {
            using (var context =db.Context())
            {
                return context.Insert<SysUser>("SysUser", sysUser)
                    .Execute() > 0;
            }
        }

        public static bool Update(SysUser sysUser)
        {
            using (var context = db.Context())
            {
                return context.Update<SysUser>("SysUser", sysUser)
                    .AutoMap(x => x.Id)
                    
                    .Where("Id", sysUser.Id)
                    
                    .Execute() > 0;
            }
        }

        public static bool Delete(SysUser sysUser) 
        {
            return Delete(sysUser.Id);
        }

        public static bool Delete(String id)
        {
            using (var context = db.Context())
            {
                return context.Sql(" DELETE FROM Product WHERE Id = @id ")
                    .Parameter("id", id)

                    .Execute() > 0;
            }
        }
    }
    
}
    
